#!/usr/bin/env fish

set hook_root (realpath (dirname (status -f)))
set project_root (realpath (dirname (status -f)))/../..

echo "Running isort..."
poetry run python3 $hook_root/isort_hook.py
set -a results $status

# echo "Running unit tests..."
# poetry run python3 -m unittest discover -s $project_root/
# set -a results $status

for i in $results
    if test $i -ne 0
        exit $i
    end
end

exit 0
